### ISSUE TITLE
por que no puedo reproducir peliculas solo series

### ISSUE THREAD

**Issue by cristian540** [j0hn/guicavane#11]
tengo un error en el programa solo me reprduce series pero cuando le doy amivies en intento reproducir algo no funciona y sale el siguiente error:

Traceback (most recent call last):
  File "/usr/share/guicavane/guicavane/GuiManager.py", line 333, in _on_file_viewer_open
    Player(self, file_object)
  File "/usr/share/guicavane/guicavane/Player.py", line 35, in __init__
    self.file_path = os.path.join(self.file_path, self.get_filename())
  File "/usr/share/guicavane/guicavane/Player.py", line 195, in get_filename
    return file_object.name.replace(os.sep, "_")
NameError: global name 'file_object' is not defined

gracias si me pudieras ayudar.

**Comment by j0hn** [comment]
Tenes razón, hay un error ahí, ya lo corrijo y subo nuevamente.

Muchas gracias!

**Comment by j0hn** [comment]
Arreglado en 1a10b45, por favor corre **git pull** si lo bajaste por git y debería estar solucionado. Gracias.

**Comment by cristian540** [comment]
muchas gracias por la rapida respuesta espero que el proyecto siga adelante y prospere.

**Comment by jorgefar2** [comment]
Hola cuando trato de acceder a guicavane desde ayer a ultima hora cuando el sitio estuvo interrumpido No puedo bajar peliculas desde aqui Si las descargo desde cuevana pero me resultaba mas util para copiarlas, grabarlas y luego reproducirlas en un repro de dvd El problema este sera por mucho tiempo o es definitivo que no vamos a poder acceder a el nunca mas? 
jorge@jorge-PC:~$ guicavane
Traceback (most recent call last):
  File "/usr/share/guicavane/guicavane/ThreadRunner.py", line 59, in check
    self.callback(result)
  File "/usr/share/guicavane/guicavane/GuiManager.py", line 147, in real_callback
    callback(result)
  File "/usr/share/guicavane/guicavane/GuiManager.py", line 310, in display_movies
    for movie in result:
  File "/usr/share/guicavane/pycavane/api.py", line 353, in get_recomended
    data = data.split("<h3>Películas destacadas</h3>")[1].split("<h3>Episodios destacados</h3>")[0]
IndexError: list index out of range

**Comment by j0hn** [comment]
guicavane it's totally broken: see https://github.com/j0hn/guicavane/issues/18 for details
