### ISSUE TITLE
Win2K SP4: guicavane no arranca.

### ISSUE THREAD

**Issue by zxMarce** [j0hn/guicavane#36]
Hola. Ví este programa y lo bajé. Al principio un MsgBox  (perdón, pero... ¡vengo de VB6!) me pidió MSVCRT90.DLL. Me bajé e instalé el redistributable de VS2008. Ahora guicavaneno da errores, pero sigue sin abrir. Guicavane.exe.log tira esto cada vez que lo arranco:

<pre>  Traceback (most recent call last):
    File "guicavane", line 12, in <module>
    File "gtk\__init__.pyc", line 40, in <module>
    File "gtk\_gtk.pyc", line 12, in <module>
    File "gtk\_gtk.pyc", line 10, in __load
  ImportError: DLL load failed: The specified procedure could not be found.</pre>

Y ahí muere. A medida que le doy doble-click se appendean bloques exactamente iguales al log. Soy Administrator-Equivalent en mi máquina. ¿Qué DLL me falta? ¿Alguien sabe si guicavane funciona en Win2K SP4?

Instalé la versión Develop (https://github.com/downloads/j0hn/guicavane/guicavane-develop.exe) y hace lo mismo.

**Comment by j0hn** [comment]
mmm prob agregando libxml2-2.dll y si no avis de nuevo =/

2011/12/23 zxMarce <
reply@reply.github.com

**Comment by zxMarce** [comment]
Probé con <b>libxml2-2.dll</b> en el directorio de Guicavane. Mismo error. Instalé en otra máquina (WinXP SP3 de la oficina, probé que Guicavane arrancara) y comprimí el directorio C:\Program Files\Guicavane, completo con subdirectorios en un .7Z y lo pasé a la máquina Win2K. Volvió a pasar exactamente lo mismo:

<PRE>Traceback (most recent call last):
  File "guicavane", line 12, in <module>
  File "gtk\__init__.pyc", line 40, in <module>
  File "gtk\_gtk.pyc", line 12, in <module>
  File "gtk\_gtk.pyc", line 10, in __load
ImportError: DLL load failed: The specified procedure could not be found.</PRE>


¿Puede estar faltando alguna subdependencia de alguna DLL que sea propia de Windows y que por usar Win2K yo no la tenga? Me refiero a una DLL que sea usada -por ejemplo- por <b>libxml2-2.dll</b> y que sea "nativa" de WinXP.

**Comment by zxMarce** [comment]
Solamente para completar un poco el panorama y veas si descubrís algo raro, te posteo un listado de mi directorio de Guicavane. Avisame si necesitás los subdirectorios:

<PRE>09/11/2010  17:41              208,384 atk.pyd
27/11/2010  18:31               76,800 bz2.pyd
02/11/2010  20:35               69,632 cairo._cairo.pyd
23/12/2011  17:14       {DIR}          etc
09/04/2011  09:21              538,324 freetype6.dll
09/04/2011  08:59              263,168 gio._gio.pyd
23/12/2011  17:14       {DIR}          Glade
09/04/2011  08:59               58,368 glib._glib.pyd
09/04/2011  08:59              113,152 gobject._gobject.pyd
09/11/2010  17:42               18,944 gtk.glade.pyd
09/11/2010  17:41            1,879,040 gtk._gtk.pyd
14/12/2011  19:48               37,376 guicavane.exe
08/01/2012  15:06                  290 guicavane.exe.log
14/12/2011  19:48               37,376 guicavane_debug.exe
23/12/2011  17:14       {DIR}          Hosts
23/12/2011  17:14       {DIR}          Images
09/04/2011  09:21              152,489 intl.dll
23/12/2011  17:14       {DIR}          lib
09/04/2011  09:21              163,406 libatk-1.0-0.dll
09/04/2011  09:21            1,182,444 libcairo-2.dll
09/04/2011  09:21              143,096 libexpat-1.dll
09/04/2011  09:21              279,059 libfontconfig-1.dll
09/04/2011  09:22              922,597 libgdk-win32-2.0-0.dll
09/04/2011  09:21              277,722 libgdk_pixbuf-2.0-0.dll
09/04/2011  09:22            1,222,972 libgio-2.0-0.dll
09/04/2011  09:22              168,833 libglade-2.0-0.dll
09/04/2011  09:22            1,243,248 libglib-2.0-0.dll
09/04/2011  09:22               36,986 libgmodule-2.0-0.dll
09/04/2011  09:22              341,425 libgobject-2.0-0.dll
09/04/2011  09:22               44,287 libgthread-2.0-0.dll
09/04/2011  09:22            4,951,479 libgtk-win32-2.0-0.dll
09/04/2011  09:22              332,196 libpango-1.0-0.dll
09/04/2011  09:22              103,139 libpangocairo-1.0-0.dll
09/04/2011  09:22              983,269 libpangoft2-1.0-0.dll
09/04/2011  09:22              108,886 libpangowin32-1.0-0.dll
09/04/2011  09:22              230,529 libpng14-14.dll
14/12/2011  19:48            2,093,257 library.zip
09/04/2011  09:22            1,225,225 libxml2-2.dll
09/11/2010  17:42              111,616 pango.pyd
09/11/2010  17:42               17,920 pangocairo.pyd
27/11/2010  18:31            2,288,640 python27.dll
27/11/2010  18:31               11,776 select.pyd
27/11/2010  18:31              635,392 sqlite3.dll
23/12/2011  17:14       {DIR}          Translations
27/11/2010  18:31              688,128 unicodedata.pyd
23/12/2011  17:21               66,607 uninstall.exe
09/04/2011  09:22              100,352 zlib1.dll
27/11/2010  18:31              285,184 _hashlib.pyd
27/11/2010  18:31               40,960 _socket.pyd
27/11/2010  18:31               57,344 _sqlite3.pyd
27/11/2010  18:31              721,920 _ssl.pyd</PRE>
