### ISSUE TITLE
Guicavane no abre

### ISSUE THREAD

**Issue by ghost** [j0hn/guicavane#37]
Tira el mismo error la versión dveveloper y la master:

xxxxx@xxxxxxxxxx:~/guicavane$ python bin/guicavane

Traceback (most recent call last):
  File "bin/guicavane", line 26, in <module>
    from guicavane import GuiManager
  File "/home/gabriel/guicavane/guicavane/**init**.py", line 1, in <module>
    from GuiManager import *
  File "/home/gabriel/guicavane/guicavane/GuiManager.py", line 16, in <module>
    import Hosts
  File "/home/gabriel/guicavane/guicavane/Hosts/**init**.py", line 6, in <module>
    import Cuevana  # FIXME: always avaliable because it's guicavane's default
  File "/home/gabriel/guicavane/guicavane/Hosts/Cuevana/**init**.py", line 4, in <module>
    import api
  File "/home/gabriel/guicavane/guicavane/Hosts/Cuevana/api.py", line 19, in <module>
    from guicavane.Utils.UrlOpen import UrlOpen
  File "/home/gabriel/guicavane/guicavane/Utils/UrlOpen.py", line 25, in <module>
    from guicavane.Constants import DEFAULT_REQUEST_TIMEOUT, CUSTOM_DNS
  File "/home/gabriel/guicavane/guicavane/Constants.py", line 13, in <module>
    from Gettext import gettext
  File "/home/gabriel/guicavane/guicavane/Gettext.py", line 11, in <module>
    import gtk.glade
ImportError: No module named glade

**Comment by j0hn** [comment]
Que distribución de gnu/linux estás usando? Si es Ubuntu proba instalando el paquete python-glade2

**Comment by ghost** [comment]
La distro es Ubuntu 11.10 u efectivamente, instalar python-glade2 solucionó el problema.
